name: MET Farevarsler Slack Bot

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run weather alerts bot
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: node met-alerts-bot.js
